deploy/injector.yaml

fix injector config

---

.gitignore
pkg/controller/controller.go

fix: fix issue #25

---

pkg/inject/api/annotation/annotations.gen.go
pkg/inject/pkg/kube/inject/inject.go

[ISSUE #42]支持pod级别sidecar注入控制

---

cmd/polaris-controller/app/options/serve.go
cmd/polaris-controller/app/polaris-controller-manager.go
common/log/config.go
common/log/default.go
common/log/logger.go
common/log/options.go
common/log/scope.go
common/log/type.go
deploy/configmap.yaml
go.mod
pkg/controller/apis.go
pkg/controller/controller.go
pkg/inject/pkg/kube/inject/concurrency.go
pkg/inject/pkg/kube/inject/inject.go
pkg/inject/pkg/kube/inject/webhook.go
pkg/polarisapi/api.go
pkg/util/address/address.go
pkg/util/helper.go
pkg/util/types.go

Fixes #43 
- 优化polaris-controller的日志打印以及日志文件滚动
- 优化service的同步，可以自动同步service的labels变化情况

[ISSUE #43] Feat issue 43

---

README-zh.md
README.md

docs: add polaris-controller support kubernetes version docs

---

deploy/kubernetes_v1.22/rbac.yaml
pkg/controller/controller.go
pkg/util/helper.go

fix: do not sync when polarismesh.cn/sync is false

---

Makefile
deploy/kubernetes_v1.21/injector.yaml
deploy/kubernetes_v1.22/injector.yaml
pkg/inject/pkg/kube/inject/webhook.go
sidecar/envoy-bootstrap-config-generator/Dockerfile
sidecar/envoy-bootstrap-config-generator/start.sh
sidecar/polaris-sidecar-init/start.sh

change method of polaris sidecar config injection

---

cmd/polaris-controller/app/polaris-controller-manager.go
common/log/type.go
deploy/kubernetes_v1.21/injector.yaml
deploy/kubernetes_v1.21/rbac.yaml
pkg/controller/controller.go
pkg/inject/pkg/kube/inject/inject.go
pkg/inject/pkg/kube/inject/webhook.go
pkg/util/types.go
sidecar/envoy-bootstrap-config-generator/Dockerfile
sidecar/envoy-bootstrap-config-generator/bootstrap_template_tls.yaml
sidecar/envoy-bootstrap-config-generator/start.sh

[feat] Support mTLS function

---

.github/workflows/docker.yml

fix:build docker tag

---

pkg/inject/pkg/kube/inject/sidecar_env.go
pkg/inject/pkg/kube/inject/webhook.go
sidecar/polaris-sidecar-init/start.sh

feat: 支持新版本的polaris-sidecar环境变量注入

---

.github/workflows/docker.yml
pkg/inject/pkg/kube/inject/sidecar_env.go
pkg/inject/pkg/kube/inject/webhook.go
sidecar/polaris-sidecar-init/start.sh

refactor sidecar inject

---

cmd/polaris-controller/app/polaris-controller-manager.go
pkg/controller/controller.go

feat: provider使用配置来创建

---

deploy/kubernetes_v1.21/injector.yaml
deploy/kubernetes_v1.22/injector.yaml
sidecar/envoy-bootstrap-config-generator/README.md

feat：仓库地址换成dockerhub的

---

deploy/kubernetes_v1.21/injector.yaml
deploy/kubernetes_v1.22/injector.yaml
pkg/inject/pkg/kube/inject/inject.go
pkg/inject/pkg/kube/inject/webhook.go

feat: 增加polaris-sidecar启动参数

---

deploy/kubernetes_v1.21/injector.yaml
deploy/kubernetes_v1.22/injector.yaml
pkg/inject/pkg/kube/inject/webhook.go

feat: 优化sidecar启动参数，去掉command配置

---

deploy/kubernetes_v1.21/injector.yaml
deploy/kubernetes_v1.22/injector.yaml
pkg/inject/pkg/kube/inject/inject.go
pkg/inject/pkg/kube/inject/webhook.go

feat: 增加webhook的日志

---

deploy/kubernetes_v1.21/injector.yaml
pkg/inject/pkg/kube/inject/webhook.go

修复mtls判断的问题

---

deploy/kubernetes_v1.21/injector.yaml
deploy/kubernetes_v1.22/injector.yaml
pkg/inject/pkg/kube/inject/webhook.go
sidecar/envoy-bootstrap-config-generator/Dockerfile

feat: 调整注入方式

---

pkg/inject/pkg/kube/inject/webhook.go

[ISSUE #79] 修复注入sidecar时解析POD的annonation出现空指针

---

deploy/kubernetes_v1.21/injector.yaml
deploy/kubernetes_v1.21/install.sh
deploy/kubernetes_v1.22/injector.yaml
deploy/kubernetes_v1.22/install.sh
pkg/inject/api/annotation/annotations.gen.go
pkg/inject/pkg/kube/inject/inject.go
pkg/inject/pkg/kube/inject/webhook.go

Fixes #79 
- 修复deploy中模版的问题
- 调整 SidecarStatus 的写入状态

Fix issue 79

---

deploy/kubernetes_v1.21/injector.yaml
pkg/inject/api/annotation/annotations.gen.go
pkg/inject/pkg/kube/inject/inject.go
pkg/inject/pkg/kube/inject/webhook.go

[ISSUE #82] 修复inject时出现json path missing value问题

---

deploy/kubernetes_v1.21/injector.yaml
pkg/inject/pkg/kube/inject/inject.go

[ISSUE #82] 修复MTLS的判断

---

deploy/kubernetes_v1.21/injector.yaml

fix:修复错误的tls判断

---

deploy/kubernetes_v1.21/injector.yaml
deploy/kubernetes_v1.22/injector.yaml
pkg/inject/pkg/kube/inject/webhook.go
sidecar/envoy-bootstrap-config-generator/start.sh
sidecar/polaris-sidecar-init/start.sh

fix:修复polaris-sidecar就近路由能力

---

pkg/inject/pkg/kube/inject/inject.go
pkg/inject/pkg/kube/inject/webhook.go
pkg/util/types.go

feat: 支持通过控制pod的annonations来决定当前注入的 sidecar 运行模式 (#89)

---

deploy/kubernetes_v1.21/polaris-client-config-tpl.yaml
pkg/inject/pkg/kube/inject/sidecar_env.go
pkg/inject/pkg/kube/inject/webhook.go
sidecar/envoy-bootstrap-config-generator/bootstrap_template.yaml

feat：支持监控数据采集的端口注入

---

pkg/controller/apis.go
pkg/util/address/address.go

feat：实例同步时，加上协议信息

---

cmd/polaris-controller/app/options/polaris.go
cmd/polaris-controller/app/polaris-controller-manager.go
pkg/cache/service_cache.go
pkg/controller/controller.go
pkg/polarisapi/api.go
pkg/util/controller_utils.go

feat: add resync process to handle polaris server failure

---

cmd/polaris-controller/app/polaris-controller-manager.go
go.mod
go.sum
pkg/controller/controller.go
pkg/util/helper.go

feat: sync polaris-controller to polaris server.

---

Makefile
docker/Dockerfile

Fixes #83 
- Docker version 19.03 or later is required.
- For the Windows environment, it is recommended to use Cygwin or Git Bash as the GNU Make shell.

feat: 引入 Docker Buildx 工具，支持跨平台构建多种系统架构的 Docker 镜像 (#83)

---

pkg/polarisapi/api.go

fix:修复LookupAccessToken判断条件

---

.github/workflows/docker.yml
Makefile

release:update makefile

---

.github/workflows/docker.yml
Makefile
cmd/polaris-controller/app/polaris-controller-manager.go
go.mod
go.sum
pkg/cache/config_cache.go
pkg/controller/apis.go
pkg/controller/configmap.go
pkg/controller/controller.go
pkg/controller/endpoint.go
pkg/controller/namespace.go
pkg/controller/rsync.go
pkg/controller/service.go
pkg/polarisapi/config_api.go
pkg/polarisapi/service_api.go
pkg/polarisapi/types.go
pkg/util/controller_utils.go
pkg/util/helper.go
pkg/util/types.go

Feat sync configmap

---

.github/workflows/golangci-lint.yml
common/log/type.go
import-formater.sh
pkg/inject/pkg/kube/inject/inject.go
pkg/inject/pkg/kube/inject/webhook.go

 feat:优化envoy的注入, 默认开启 inbound 拦截

---

.github/workflows/codeql.yml
.github/workflows/docker.yml
.github/workflows/golangci-lint.yml
.github/workflows/release.yml
.github/workflows/testing.yml
cmd/polaris-controller/app/polaris-controller-manager.go
deploy/kubernetes_v1.21/helm/templates/controller-statefulset.yaml
deploy/kubernetes_v1.21/polaris-controller.yaml
deploy/kubernetes_v1.22/helm/templates/controller-statefulset.yaml
deploy/kubernetes_v1.22/polaris-controller.yaml
pkg/controller/controller.go

fix:make build and push image fail

---

cmd/polaris-controller/app/client_builder.go
cmd/polaris-controller/app/options/options.go
deploy/kubernetes_v1.21/rbac.yaml
deploy/kubernetes_v1.22/rbac.yaml
go.mod
go.sum
pkg/controller/apis.go
pkg/controller/configmap.go
pkg/controller/controller.go
pkg/controller/endpoint.go
pkg/controller/namespace.go
pkg/controller/rsync.go
pkg/controller/service.go
pkg/controller/types.go
pkg/polarisapi/config_api.go
pkg/polarisapi/service_api.go
pkg/polarisapi/types.go
pkg/util/flag/flags.go
pkg/util/helper.go

fix: 修复同步 service/configmap 数据丢失问题

---

.github/workflows/release.yml

fix:update envoy version

---

cmd/polaris-controller/app/client_builder.go
deploy/kubernetes_v1.21/injector.yaml
deploy/kubernetes_v1.22/injector.yaml
pkg/controller/apis.go
pkg/inject/pkg/kube/inject/webhook.go
pkg/polarisapi/service_api.go
pkg/util/address/address.go
pkg/util/flag/flags.go

未就绪pod同步为流量隔离

---

deploy/kubernetes_v1.21/helm/templates/controller-configmap-sidecar.yaml
deploy/kubernetes_v1.21/injector.yaml
deploy/kubernetes_v1.22/helm/templates/controller-configmap-sidecar.yaml
deploy/kubernetes_v1.22/injector.yaml
go.mod
pkg/util/address/address.go
sidecar/envoy-bootstrap-config-generator/bootstrap_template.yaml
sidecar/envoy-bootstrap-config-generator/bootstrap_template_tls.yaml

fix:回滚envoy-sidecar相关配置, 解决无法通过域名接入北极星服务端问题

---

sidecar/envoy-bootstrap-config-generator/bootstrap_template.yaml
sidecar/envoy-bootstrap-config-generator/bootstrap_template_tls.yaml

set envoy grpc.max_receive_message_length to -1

---

Makefile
cmd/polaris-controller/app/options/polaris.go

fix:check sync config enable occur nil panic

---

Makefile
cmd/polaris-controller/app/options/polaris.go
pkg/controller/configmap.go
pkg/controller/controller.go
pkg/controller/service.go
pkg/util/types.go

fix:修复非预期同步的数据频繁处理问题

---

cmd/polaris-controller/app/polaris-controller-manager.go
pkg/controller/configmap.go
pkg/controller/controller.go
pkg/polarisapi/service_api.go

fix:修复配置中心链接端口错误问题

---

pkg/controller/configmap.go

fix:调整配置同步的开关判断

---

deploy/kubernetes_v1.21/helm/templates/_params.tpl
deploy/kubernetes_v1.21/helm/templates/controller-clusterrole.yaml
deploy/kubernetes_v1.21/helm/templates/controller-configmap-sidecar.yaml
deploy/kubernetes_v1.21/kubernetes/injector.yaml
deploy/kubernetes_v1.21/kubernetes/rbac.yaml
deploy/kubernetes_v1.22/helm/templates/controller-clusterrole.yaml
deploy/kubernetes_v1.22/helm/templates/controller-configmap-sidecar.yaml
deploy/kubernetes_v1.22/kubernetes/injector.yaml
deploy/kubernetes_v1.22/kubernetes/polaris-controller.yaml
deploy/kubernetes_v1.22/kubernetes/rbac.yaml
sidecar/envoy-bootstrap-config-generator/bootstrap_template.yaml
sidecar/envoy-bootstrap-config-generator/bootstrap_template_odcds.yaml
sidecar/envoy-bootstrap-config-generator/bootstrap_template_tls.yaml
sidecar/envoy-bootstrap-config-generator/bootstrap_template_tls_odcds.yaml

fix:polaris-sidecar linsten unix socket file share to envoy

---

Makefile
cmd/polaris-controller/app/polaris-controller-manager.go
deploy/kubernetes_v1.21/kubernetes/install.sh
deploy/kubernetes_v1.22/kubernetes/install.sh
pkg/inject/pkg/kube/inject/apply/base/patch.go
pkg/inject/pkg/kube/inject/apply/javaagent/patch.go
pkg/inject/pkg/kube/inject/apply/mesh/patch.go
pkg/inject/pkg/kube/inject/pod_patch.go
pkg/inject/pkg/kube/inject/webhook.go

feat:support inject java agent to user pod

---

deploy/kubernetes_v1.21/helm/templates/controller-configmap-javaagent.yaml
deploy/kubernetes_v1.21/helm/templates/controller-statefulset.yaml
deploy/kubernetes_v1.21/kubernetes/javaagent-configmap.yaml
deploy/kubernetes_v1.21/kubernetes/polaris-controller.yaml
deploy/kubernetes_v1.22/helm/templates/controller-configmap-javaagent.yaml
deploy/kubernetes_v1.22/helm/templates/controller-statefulset.yaml
deploy/kubernetes_v1.22/kubernetes/javaagent-configmap.yaml
deploy/kubernetes_v1.22/kubernetes/polaris-controller.yaml
pkg/inject/pkg/kube/inject/apply/javaagent/patch.go
pkg/inject/pkg/kube/inject/webhook.go

fix:修复java-agent注入时plugin.enable格式不对

---

pkg/inject/pkg/kube/inject/apply/javaagent/patch.go
pkg/inject/pkg/kube/inject/inject.go

fix:调整annonations的注解名称

---

pkg/inject/pkg/kube/inject/inject.go
pkg/inject/pkg/kube/inject/webhook.go

fix:修复kubernetes1.22+版本无法正确注入javaagent

---

pkg/controller/apis.go
pkg/controller/service.go
pkg/polarisapi/service_api.go
pkg/util/controller_utils.go
pkg/util/types.go

支持overide北极星名字和Namespace，解决大小写和-问题

---

deploy/kubernetes_v1.22/kubernetes/install.sh
deploy/kubernetes_v1.22/kubernetes/polaris-controller.yaml

Fixes #
1. fix error in install.sh, it will result in error if awk print { } included /bin/bash.
2. log volumeMounts mismatch logs.

fix command not found in install.sh 

---

build.sh
deploy/kubernetes_v1.21/kubernetes/install.sh

Fixes #
fix error and close #117 
Also there are the same mistake in build.sh, as far as i concerned they should be fix, otherwise it will result in error, not expected output.

fix error in install.sh and build.sh

---

deploy/kubernetes_v1.21/kubernetes/javaagent-configmap.yaml

feat: add spring cloud 2023 configuration

---

deploy/kubernetes_v1.21/kubernetes/javaagent-configmap.yaml

fix: add campus as location level

---

deploy/kubernetes_v1.21/kubernetes/javaagent-configmap.yaml

support location campus configuration

---

deploy/kubernetes_v1.21/kubernetes/javaagent-configmap.yaml
deploy/kubernetes_v1.22/helm/templates/controller-configmap-javaagent.yaml
deploy/kubernetes_v1.22/kubernetes/javaagent-configmap.yaml

feat: new add javaagent spring cloud 2023 plugin configs

---

Makefile
cmd/polaris-controller/app/polaris-controller-manager.go
pkg/inject/pkg/kube/inject/inject.go
pkg/inject/pkg/kube/inject/webhook.go
sidecar/polaris-sidecar-init/Dockerfile

fix:修复javaagent注入配置存在问题

---

deploy/kubernetes_v1.21/kubernetes/javaagent-configmap.yaml
deploy/kubernetes_v1.22/kubernetes/javaagent-configmap.yaml

change agent configmap
